	name: Main Github Actions
on:
  push:
    branches:
      - 'master' # Set branch of the GH repo to push
jobs:
Report:
    name: Tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.9.0' # In command line run “node -v” and choose your version
      - run: npm ci
#      - run: npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
      - name: NPM install
        run: npm install
      - name: run test
        run: npm run test:headless # Our name of the headless script
      - name: Copy History
        if: always()
        run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
      - name: Generate Report
        if: always()
        run: npm run allure:generate # Name of the allure generate script
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results                    
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report        
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: master # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.
          target-folder: docs
      - name: Pushes docs to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        if: always()
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }} 
        with:
          source-directory: 'docs'
          destination-github-username: 'zblashchuk' # Your username
          destination-repository-name: 'telnyx-wdio-allure-docker-' 
          user-email: zblashchukr@gmail.com 
          target-branch: main 


   

   

      
       